### ISSUE TITLE
select where to put the class

### ISSUE THREAD

**Issue by robgal519** [tzAcee/cpp-class-creator#1]
First, I really like what you have done, but I would have some minor suggestions that would improve the experience.

- let user decide where the new class will be placed (default as root of the project is fine, but users should be able to easily pick where to put it)

- add check boxes for:
  - deleting copy constructor
  - deleting move constructor
  - etc...
  It would be nice to be explicit, so that compiler would not auto generate any operator or function (you can always signal that it is default implementation)

- add inheritance
  it would be nice if you could integrate it with some other c++ extension, that is aware of the existing classes, and their virtual functions
  For start simply adding possibility to inherent from some class would be nice, and later, let user decide what virtual functions will be implemented in newly created class

Thank you for your kind work, I will be looking forward how this project will evolve.

**Comment by fleexo** [comment]
Thank you for your feed back. I'll work on it as soon as I have time.
>     * let user decide where the new class will be placed (default as root of the project is fine, but users should be able to easily pick where to put it)
Just implemented it, thank you (again :b)

**Comment by xkaraman** [comment]
You should avoid using `workspace.rootPath` as it seems to get the paths wrong. In my case it defines the C:/../AppData\Local\Programs\Microsoft VS Code as `dir` variable. 

Instead use `workspace.workspaceFolders`. Don't know how much of rework needs to be done. [StackOverflow](https://stackoverflow.com/questions/57822840/how-to-get-path-for-currently-open-tab-files-root-path)

Also you could implement different destination for header and source files since most of the times, they are in `include/` or `src/` folder respectively.
